name: Sync to Hugging Face
on:
  push:
    branches: [main] # Se activa cada vez que subes algo a la rama 'main'
  workflow_dispatch: # Permite activarlo manualmente

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://SantiagoG500:$HF_TOKEN@huggingface.co/spaces/SantiagoG500/Numerical_methods_calculator
